// ─── data.js ── Cooking Study Plan: 208 Wochen ─────────────────────────

export const PHASES = [
  { id:1, name:"Grundlagen", weeks:"1–52", color:"#22c55e", desc:"Klassische französische Methoden, Messerkunde, Fonds, Saucen, Proteine, Patisserie" },
  { id:2, name:"Horizonterweiterung", weeks:"53–104", color:"#60a5fa", desc:"Weltküchen: Italienisch, Japanisch, Chinesisch, Österreich, Spanisch, Koreanisch, Mexikanisch, Nahöstlich" },
  { id:3, name:"Fortgeschrittene Techniken", weeks:"105–156", color:"#a78bfa", desc:"Molekularküche, Fermentation, Sous-vide, modernistisches Anrichten" },
  { id:4, name:"Meisterschaft", weeks:"157–208", color:"#f59e0b", desc:"Degustationsmenüs, saisonales Kochen, alkoholfreie Getränkebegleitung, persönlicher Stil" },
];

export const RATING_LABELS = {
  0: { label:"–", desc:"Noch nicht bewertet", color:"#4a5270" },
  1: { label:"1", desc:"Nicht geschafft", color:"#ef4444" },
  2: { label:"2", desc:"Mit Schwierigkeiten", color:"#f97316" },
  3: { label:"3", desc:"Solide", color:"#eab308" },
  4: { label:"4", desc:"Stolz!", color:"#22c55e" },
  5: { label:"5", desc:"Meisterhaft", color:"#818cf8" },
};

export const ARRIVAL_CRITERIA = [
  "Finales 7-Gänge-Degustationsmenü erfolgreich ausgeführt",
  "Alkoholfreie Getränkebegleitung zu jedem Gang entwickelt",
  "Mindestens 3 Fermentationsprojekte (Kimchi, Miso, Kombucha) laufen dauerhaft",
  "Ein Signatur-Gericht identifiziert und perfektioniert",
  "Portfolio mit mind. 10 professionellen Fotos",
  "5 Muttersaucen ohne Rezept zubereiten können",
  "Ein Huhn in unter 5 Minuten in 8 Teile zerlegen",
  "Sauerteig-Starter seit 6+ Monaten am Leben",
  "Teilnahme: Stage / Pop-up / Supper Club / Wettbewerb",
];

// Helper for placeholder weeks
const pw = (w, phase, theme) => ({ w, phase, theme, dish:"", source:"", technique:"", check:"", ownBook:false });

export const WEEKS = [

  // ════════════════════════════════════════════════════════════════════════
  // PHASE 1: GRUNDLAGEN (Wochen 1–52)
  // ════════════════════════════════════════════════════════════════════════

  { w:1, phase:1, theme:"Messerkunst I: Die klassischen Schnitte", dish:"Gemüsesuppe mit Brunoise", source:"Jacques Pépin – New Complete Techniques", technique:"Brunoise, Julienne, Chiffonade, Batonnet, Paysanne, Tourne", check:"Kannst du eine Zwiebel in unter 3 Min. gleichmäßig in Brunoise schneiden?", ownBook:false },
  { w:2, phase:1, theme:"Das französische Omelett", dish:"Omelett (classique, 6-fach gefaltet)", source:"Jacques Pépin – Technique", technique:"Hitzeführung, Pfannenkontrolle", check:"Omelett in 30 Sekunden, ohne Farbe, 6-fach gefaltet?", ownBook:false },
  { w:3, phase:1, theme:"Fond / Hühnerbrühe (Fond blanc de volaille)", dish:"Hühnerbrühe + Remouillage", source:"Institut Paul Bocuse Gastronomique / Thomas Keller – TFL", technique:"Extraktion, Temperatur, Gelatine, Abschäumen", check:"Geliert dein Fond im Kühlschrank?", ownBook:true },
  { w:4, phase:1, theme:"Zwiebeln & langsames Karamellisieren", dish:"Soupe à l'oignon gratinée", source:"Julia Child – Mastering the Art of French Cooking", technique:"Déglaçage, Fond-Reduktion", check:"Sind deine Zwiebeln tiefgolden nach 45+ Minuten? Käsekruste vollständig?", ownBook:false },
  { w:5, phase:1, theme:"Muttersaucen I: Béchamel", dish:"Croque Monsieur", source:"Auguste Escoffier – Le Guide Culinaire", technique:"Roux (drei Stufen: weiß, blond, braun), Löffelrücken-Konsistenz", check:"Béchamel klumpenfrei?", ownBook:true },
  { w:6, phase:1, theme:"Muttersaucen II: Velouté", dish:"Blanquette de veau", source:"Escoffier – Le Guide Culinaire", technique:"Velouté plus Liaison (Eigelb + Sahne)", check:"Sauce seidig glatt, ganzes Gericht am Kopf balanciert?", ownBook:true },
  { w:7, phase:1, theme:"Muttersaucen III: Espagnole", dish:"Short Ribs in Demi-Glace", source:"Escoffier – Le Guide Culinaire", technique:"Brauner Fond, Demi-Glace, Reduktion", check:"Sauce konzentriert, nappiert den Löffel?", ownBook:true },
  { w:8, phase:1, theme:"Muttersaucen IV: Tomatensauce", dish:"Sugo + Tomaten-Concassé", source:"Escoffier / Marcella Hazan", technique:"Langkochen, Concassé als eigenständige Technik", check:"Unterschied zwischen Sugo und Concassé erklären können?", ownBook:false },
  { w:9, phase:1, theme:"Muttersaucen V: Hollandaise", dish:"Eggs Benedict", source:"Escoffier + Serious Eats", technique:"Emulsion: Eigelb am Rand zu Fett, Wasserbad", check:"Hollandaise stabil? Varianten (Estragon, Schalotte) beherrscht?", ownBook:false },
  { w:10, phase:1, theme:"Steak – Maillard-Reaktion", dish:"Gegrilltes Steak, Steak au poivre", source:"Kenji – Food Lab / Escoffier", technique:"Maillard-Reaktion, Saucenbau (Pan Sauce)", check:"Gleichmäßige Kruste, rosa Kern, Sauce transformiert?", ownBook:false },
  { w:11, phase:1, theme:"Soufflé – Eierschaum-Wissenschaft", dish:"Soufflé au fromage", source:"Julia Child – MAFC / Bruno Albouze", technique:"Eischnee schlagen, Unterheben, Ofenverhalten", check:"Soufflé perfekt aufgegangen, Apfel-Art?", ownBook:false },
  { w:12, phase:1, theme:"Rührei – On-and-off-Heat", dish:"Scrambled Eggs, Gordon Ramsay Style", source:"Jacques Pépin / Gordon Ramsay", technique:"Cremigkeit durch Geduld, kein Überkochen", check:"Cremig, großflockig?", ownBook:false },
  { w:13, phase:1, theme:"Geflügel I: Ganzes Huhn braten", dish:"Poulet rôti (Thomas Keller Methode)", source:"Thomas Keller – Ad Hoc at Home", technique:"Trockene Haut, Kerntemperatur, Ruhezeit", check:"Haut knusprig, Fleisch saftig?", ownBook:true },
  { w:14, phase:1, theme:"Geflügel II: Huhn zerlegen & Suprême", dish:"Hühnersuprême mit Jus", source:"Jacques Pépin – Technique", technique:"Huhn in 8 Teile zerlegen, Brustfilet lösen", check:"Zerlegen sauber und schnell? Suprême saftig?", ownBook:false },
  { w:15, phase:1, theme:"Schmoren I: Coq au vin", dish:"Coq au vin", source:"Julia Child – MAFC", technique:"Anbraten, Déglaçage, Schmoren in Flüssigkeit", check:"Fleisch gabelzart? Sauce reduziert?", ownBook:false },
  { w:16, phase:1, theme:"Schmoren II: Boeuf bourguignon", dish:"Boeuf bourguignon", source:"Julia Child – MAFC", technique:"Fond, Wein-Reduktion, Schmortechnik", check:"Komplex? Vielschichtig? Nicht breiig?", ownBook:false },
  { w:17, phase:1, theme:"Fisch I: Filetieren & Hautseite", dish:"Gebratener Lachs, Beurre blanc", source:"Jacques Pépin – Technique", technique:"Filetieren, Hautseite knusprig, Beurre blanc", check:"Haut kross, Kern glasig?", ownBook:false },
  { w:18, phase:1, theme:"Fisch II: Pochieren & Meunière", dish:"Sole meunière", source:"Julia Child – MAFC / Escoffier", technique:"Pochieren, Meunière-Technik, Zitrone, Petersilie", check:"Butter nussig-braun, Fisch gerade gar?", ownBook:false },
  { w:19, phase:1, theme:"Salate & Vinaigrette", dish:"Salade Lyonnaise", source:"Escoffier / Thomas Keller", technique:"Vinaigrette-Komposition (3:1), Frisée vs. andere Bitter-Salate", check:"Vinaigrette emulgiert, Salat ausgewogen?", ownBook:false },
  { w:20, phase:1, theme:"Sautieren – Drei-Schritt-Technik", dish:"Steak au poivre (Restaurant-Methode)", source:"Kenji – Food Lab", technique:"Sautieren: Pfanne heiß, Fett, Protein", check:"Kruste gleichmäßig, Saucenbau perfekt?", ownBook:false },
  { w:21, phase:1, theme:"Gemüse I: Confit byaldi (Ratatouille)", dish:"Confit byaldi (Thomas Keller)", source:"Thomas Keller – TFL / ChefSteps", technique:"Minimale Intervention, Zucker bis zur natürlichen Mitte", check:"Gemüse perfekt weich, Schichten intakt?", ownBook:true },
  { w:22, phase:1, theme:"Gemüse II: Wurzelgemüse-Rösten", dish:"Geröstete Wurzelgemüse mit Fond brun", source:"Thomas Keller – Ad Hoc at Home", technique:"Pastinake, Karotte: Maillard durch Verdampfung, dunkler Fond", check:"Karamellisierung gleichmäßig?", ownBook:true },
  { w:23, phase:1, theme:"Quiche & Mürbeteig (Pâte brisée)", dish:"Quiche Lorraine", source:"Julia Child – MAFC", technique:"Fraisage (Teigbildung), Blindbacken", check:"Boden blind gebacken, keine Schrumpfung, keine Blasen?", ownBook:false },
  { w:24, phase:1, theme:"Tarte aux pommes", dish:"Tarte aux pommes (Apfeltarte)", source:"Jacques Pépin – Technique", technique:"Mürbeteig beherrschen, Schichten, Aprikotur-Glasur", check:"Boden knusprig, Äpfel gleichmäßig gelegt?", ownBook:false },
  { w:25, phase:1, theme:"Blätterteig (Pâte feuilletée)", dish:"Vol-au-vent mit Rahmchampignons", source:"Julia Child – MAFC / Bruno Albouze", technique:"Detrempe + Beurrage, doppelte Touren", check:"Blätterteig hoch aufgegangen? Pilzfüllung cremig?", ownBook:false },
  { w:26, phase:1, theme:"Brandteig I: Gougères", dish:"Gougères (Gruyère-Kugeln)", source:"Jacques Pépin – Technique", technique:"Brandteig: Herd + Ofen, Spritzbeutel", check:"Hohl innen, knusprig außen?", ownBook:false },
  { w:27, phase:1, theme:"Brandteig II: Profiteroles", dish:"Profiteroles mit Schokoladen-Sauce", source:"Jacques Pépin / Bruno Albouze", technique:"Brandteig + Vanillecreme", check:"Profiteroles gleichmäßig, Creme fließend?", ownBook:false },
  { w:28, phase:1, theme:"Zusammengesetzte Saucen", dish:"Sauce Robert + Côtelettes de porc", source:"Escoffier – Le Guide Culinaire", technique:"Muttersauce ableiten (Maître d'hôtel, Café de Paris)", check:"Sauce Robert sofort reproduzierbar?", ownBook:true },
  { w:29, phase:1, theme:"Consommé", dish:"Consommé de boeuf", source:"Escoffier – Le Guide Culinaire", technique:"Klärung mit Eiweiß (Clarification), Clearmeat", check:"Consommé vollkommen klar?", ownBook:true },
  { w:30, phase:1, theme:"Kartoffel-Techniken", dish:"Pommes dauphine / Gratin dauphinois", source:"Escoffier / Jacques Pépin", technique:"Verschiedene Garmethoden, Konsistenz", check:"Pommes dauphine innen luftig, außen knusprig?", ownBook:false },
  { w:31, phase:1, theme:"Terrinen & Pâtés I", dish:"Terrine de campagne", source:"Jacques Pépin – Technique", technique:"Farce, Einlage, Aspikschicht", check:"Schnitt sauber, Farce gleichmäßig?", ownBook:false },
  { w:32, phase:1, theme:"Risotto – Stärke-Management", dish:"Risotto alla Milanese", source:"Marcella Hazan / Escoffier", technique:"Tostatura, Fond zugeben, Mantecatura", check:"Cremig-fließend (all'onda), Kern noch bissfest?", ownBook:false },
  { w:33, phase:1, theme:"Frische Pasta I", dish:"Tagliatelle al ragù bolognese", source:"Marcella Hazan – Essentials", technique:"Teig kneten, Ausrollen, Ragù (Soffritto, langsam)", check:"Pasta al dente, Ragù samtig?", ownBook:false },
  { w:34, phase:1, theme:"Frische Pasta II: Gefüllte Pasta", dish:"Ravioli (Ricotta + Spinat)", source:"Marcella Hazan / Evan Funke", technique:"Füllung, Formen, Verschließen ohne Luft", check:"Ravioli gleichmäßig, nicht aufgeplatzt?", ownBook:false },
  { w:35, phase:1, theme:"Italienisch: Agnolotti dal plin", dish:"Agnolotti dal plin mit Salbei-Butter", source:"Massimo Bottura – Never Trust a Skinny Italian Chef", technique:"Piemonteser Technik: Kneifen (plin)", check:"Gleichmäßig geformt, Salbei-Butter nussig?", ownBook:false },
  { w:36, phase:1, theme:"Italienisch: Osso buco", dish:"Osso buco alla milanese + Gremolata", source:"Marcella Hazan – Essentials", technique:"Schmoren, Markbein, Gremolata", check:"Fleisch vom Knochen gelöst, Mark zart?", ownBook:false },
  { w:37, phase:1, theme:"Pizza & Hochtemperatur-Backen", dish:"Pizza Margherita (neapolitanisch)", source:"Vito Iacopelli / Ken Forkish", technique:"Hohe Hydration, 450°C simulieren (Backstahl/Grill)", check:"Rand aufgegangen, Sohle leopardenfleckig?", ownBook:false },
  { w:38, phase:1, theme:"Focaccia & Ciabatta", dish:"Focaccia Genovese", source:"Nancy Silverton – Mozza", technique:"Hohe Hydration, Olivenöl, Struktur + Dressing", check:"Fluffig, knusprige Unterseite?", ownBook:false },
  { w:39, phase:1, theme:"Pasta: Spaghetti & Meeresfrüchte", dish:"Spaghetti alle vongole", source:"Marcella Hazan – Essentials", technique:"Meeresfrüchte: minimaler Eingriff, Timing", check:"Muscheln gerade offen, Pasta al dente?", ownBook:false },
  { w:40, phase:1, theme:"Fisch im Cartoccio", dish:"Fisch in Pergament (en papillote)", source:"Jacques Pépin – Technique", technique:"Dampfgaren im Päckchen, Duft-Theatralik", check:"Päckchen bläht sich auf? Fisch perfekt gar?", ownBook:false },
  { w:41, phase:1, theme:"Japanisch I: Dashi & Umami", dish:"Ichiban-Dashi + Misosuppe", source:"Shizuo Tsuji – Japanese Cooking: A Simple Art", technique:"Kombu + Katsuobushi, Umami-Synergie", check:"Dashi klar, Umami-Tiefe spürbar?", ownBook:false },
  { w:42, phase:1, theme:"Japanisch II: Chawanmushi", dish:"Chawanmushi (Eierstich, gedämpft)", source:"Shizuo Tsuji – Japanese Cooking", technique:"Dampfgaren, Ei-Dashi-Verhältnis, seidig-glatt", check:"Oberfläche glatt, keine Löcher im Ei?", ownBook:false },
  { w:43, phase:1, theme:"Japanisch III: Sushi & Nigiri", dish:"Nigiri-Sushi (Hirazukuri: Maguro, Ebi)", source:"Masaharu Morimoto – New Art", technique:"Shari (Reis exakt), Fisch schneiden, Formen", check:"Reis locker, Fisch frisch arrangiert?", ownBook:false },
  { w:44, phase:1, theme:"Japanisch IV: Tempura", dish:"Tempura (Eiswasser-Teig + Tentsuyu)", source:"Shizuo Tsuji – Japanese Cooking", technique:"Eiswasser-Teig, Temperaturkontrolle", check:"Knusprig, kaum Fett, Ergebnis hauchzart?", ownBook:false },
  { w:45, phase:1, theme:"Japanisch V: Tonkatsu", dish:"Tonkatsu + Krautsalat", source:"Ivan Orkin – Ivan Ramen", technique:"Panko, europäisch-japanische Hybrid-Technik", check:"Doppelt paniert, knusprig, saftig?", ownBook:false },
  { w:46, phase:1, theme:"Ramen (3-Tage-Projekt)", dish:"Tonkotsu Ramen (12h+ Brühe, Tare, Toppings)", source:"Ivan Orkin – Ivan Ramen", technique:"Brühe 6:30h+, Tare, Nudeln, Toppings (Chashu, Ajitsuke Ei)", check:"Brühe milchig-weiß, Tare ausbalanciert?", ownBook:false },
  { w:47, phase:1, theme:"Japanisch: Yakitori & Izakaya", dish:"Yakitori (Herz, Knorpel, Schenkel)", source:"Shizuo Tsuji / Ivan Orkin", technique:"Binchotan-Grillen (oder Annäherung), Tare (Shio/Tare)", check:"Fleisch saftig, Tare karamellisiert?", ownBook:false },
  { w:48, phase:1, theme:"Japanisch: Black Cod Miso", dish:"Black Cod mit Miso-Marinade (Nobu-Stil)", source:"Nobu Matsuhisa – Nobu Cookbook", technique:"Miso-Marinade (24h+), sanftes Garen", check:"Glasur karamellisiert, Fisch butterweich?", ownBook:false },
  { w:49, phase:1, theme:"Chinesisch: Wok-Hei & Sichuan I", dish:"Kung Pao Chicken", source:"Fuchsia Dunlop – The Food of Sichuan", technique:"Wok-Hei, Velveting, Aromaten (Ingwer, Knoblauch)", check:"Wok-Aroma, Huhn zart durch Velveting?", ownBook:false },
  { w:50, phase:1, theme:"Chinesisch: Mapo Tofu", dish:"Mapo Tofu", source:"Fuchsia Dunlop – The Food of Sichuan", technique:"Doubanjiang, Málà (betäubend-scharf), Seidentofu", check:"Sichuan-Pfeffer betäubt? Tofu intakt?", ownBook:false },
  { w:51, phase:1, theme:"Chinesisch: Xiao Long Bao", dish:"Xiao Long Bao (Suppenknödel)", source:"Fuchsia Dunlop – Every Grain of Rice", technique:"Aspik-Füllung, 18+ Falten, Dampfgaren", check:"Suppe im Inneren, 18+ Falten geschafft?", ownBook:false },
  { w:52, phase:1, theme:"Phase-1-Abschluss: Kaiseki-inspiriertes Menü", dish:"3-Gänge-Menü (saisonal, ästhetisch)", source:"Alle Phase-1-Quellen", technique:"Menüplanung, Pacing, Ästhetik, Mise en place", check:"Menü harmonisch? Timing nahtlos? Anrichten gelungen?", ownBook:false },

  // ════════════════════════════════════════════════════════════════════════
  // PHASE 2: HORIZONTERWEITERUNG (Wochen 53–104)
  // ════════════════════════════════════════════════════════════════════════

  { w:53, phase:2, theme:"Chinesisch: Dim Sum – Char Siu Bao", dish:"Char Siu Bao (BBQ-Pork-Brötchen)", source:"Fuchsia Dunlop – Every Grain of Rice", technique:"Hefeteig, Lotusblatt-Dampf, Char-Siu-Glasur", check:"Teig fluffig, Füllung saftig?", ownBook:false },
  { w:54, phase:2, theme:"Chinesisch: Peking-Ente", dish:"Peking-Ente (vereinfachte Methode)", source:"Fuchsia Dunlop – Every Grain of Rice", technique:"Hoisin, Lufttrocknung, Kantonesisch", check:"Haut knusprig-glasig, Fleisch saftig?", ownBook:false },
  { w:55, phase:2, theme:"Österreichisch I: Wiener Schnitzel", dish:"Wiener Schnitzel (Kalbfleisch)", source:"Ewald Plachutta – Die gute Küche", technique:"Panieren: soufflierte Panade, Butterschmalz", check:"Panade wellig-souffliert, kein Anliegen?", ownBook:true },
  { w:56, phase:2, theme:"Österreichisch II: Tafelspitz", dish:"Tafelspitz mit Apfelkren + Schnittlauchsauce", source:"Ewald Plachutta – Die gute Küche", technique:"Sanftes Sieden, Brühe klar, Beilagen klassisch", check:"Fleisch zart, Brühe klar, Kren frisch gerieben?", ownBook:true },
  { w:57, phase:2, theme:"Österreichisch III: Sachertorte", dish:"Sachertorte", source:"Plachutta / Schuhbeck", technique:"Schokoladenbiskuit, Aprikotur, Schokoladeglasur", check:"Glasur spiegelglatt, Schnitt sauber?", ownBook:true },
  { w:58, phase:2, theme:"Österreichisch IV: Kaiserschmarrn", dish:"Kaiserschmarrn mit Zwetschkenröster", source:"Plachutta – Die gute Küche", technique:"Pfanne + Ofen, Zerreißen, Karamellisieren", check:"Fluffig, karamellisiert, Zwetschken fruchtig-säuerlich?", ownBook:true },
  { w:59, phase:2, theme:"Deutsch: Schweinshaxe", dish:"Schweinshaxe (Ofenmethode)", source:"Alfons Schuhbeck – Meine bayerische Küche", technique:"Blitz-Brühen, Gusseisen, knusprige Schwarte", check:"Schwarte knusprig, Fleisch saftig?", ownBook:false },
  { w:60, phase:2, theme:"Deutsch: Sauerbraten & Rotkohl", dish:"Sauerbraten mit Rotkohl + Semmelknödel", source:"Alfons Schuhbeck – Meine bayerische Küche", technique:"Beizen (3+ Tage), Schmorbraten, Rotkohl", check:"Sauce sämig, Rotkohl ausbalanciert?", ownBook:false },
  { w:61, phase:2, theme:"Spanisch I: Tortilla Española", dish:"Tortilla Española", source:"José Andrés – Tapas", technique:"Kartoffeln in Olivenöl konfieren, Ei stocken", check:"Innen cremig-fließend, Wendung gelungen?", ownBook:false },
  { w:62, phase:2, theme:"Spanisch II: Pulpo a la gallega", dish:"Pulpo a la gallega", source:"José Andrés – Tapas", technique:"Oktopus-Zartmachen (Einfrieren/Kochen), Pimentón", check:"Oktopus zart, nicht gummiartig?", ownBook:false },
  { w:63, phase:2, theme:"Spanisch III: Pintxos (Baskenland)", dish:"Pintxos-Auswahl (Gilda, Jamón-Kroketten)", source:"José Andrés – Tapas", technique:"Ein-Biss-Werke, Zahnstochertechnik, Baskenland-Auswahl", check:"Optisch ansprechend, Geschmack komplex?", ownBook:false },
  { w:64, phase:2, theme:"Spanisch IV: Bacalao al pil-pil", dish:"Bacalao al pil-pil", source:"José Andrés – Tapas", technique:"Gelatine-Emulsion durch Schwenken", check:"Sauce emulgiert, Fisch zart?", ownBook:false },
  { w:65, phase:2, theme:"Koreanisch I: Kimchi & Gochugaru", dish:"Kimchi (Baechu-Kimchi)", source:"Maangchi – Real Korean Cooking", technique:"Salzen, Gochugaru-Paste, Fermentation", check:"Gärung aktiv nach 3+ Tagen?", ownBook:false },
  { w:66, phase:2, theme:"Koreanisch II: Bulgogi", dish:"Bulgogi", source:"Maangchi – Real Korean Cooking", technique:"Marinieren, Birne-Enzym, Tischgrill", check:"Fleisch zart, karamellisiert, nicht angebrannt?", ownBook:false },
  { w:67, phase:2, theme:"Koreanisch III: Kimchi-Jjigae", dish:"Kimchi-Jjigae (Eintopf)", source:"Maangchi – Real Korean Cooking", technique:"Gereiftes Kimchi verwenden, Tofu, Schweinebauch", check:"Tiefe Umami, nicht nur scharf?", ownBook:false },
  { w:68, phase:2, theme:"Koreanisch IV: Korean Fried Chicken", dish:"Yangnyeom Chicken (Double-Fry)", source:"Maangchi – Real Korean Cooking", technique:"Double-Fry (erst niedrig, dann hoch), Sauce", check:"Knusprig trotz Sauce? Temperaturkontrolle?", ownBook:false },
  { w:69, phase:2, theme:"Koreanisch V: Japchae & Banchan", dish:"Japchae + Banchan-Auswahl", source:"Maangchi – Real Korean Cooking", technique:"Glasnudeln, Sesam, Banchan als Spread", check:"Nudeln nicht verklebt, Banchan ausgewogen?", ownBook:false },
  { w:70, phase:2, theme:"Mexikanisch I: Mole Negro", dish:"Mole Negro (30+ Zutaten)", source:"Diana Kennedy – Essential Cuisines of Mexico", technique:"Chilis rösten, Schokolade, Komplexität aufbauen", check:"Alle Schichten schmeckbar? Nicht zu bitter?", ownBook:false },
  { w:71, phase:2, theme:"Mexikanisch II: Carnitas & Salsa", dish:"Carnitas + Salsa verde", source:"Diana Kennedy / Rick Bayless", technique:"Konfieren in eigenem Fett, Koriander-Salsa", check:"Fleisch außen knusprig, innen zart?", ownBook:false },
  { w:72, phase:2, theme:"Nahöstlich I: Lamb Shawarma", dish:"Lamb Shawarma mit Za'atar + Tahini", source:"Yotam Ottolenghi – Jerusalem / NOPI", technique:"Marinieren, Za'atar, Tahini-Sauce", check:"Gewürzbalance? Tahini cremig?", ownBook:false },
  { w:73, phase:2, theme:"Nahöstlich II: Mejadra", dish:"Mejadra (Linsen + Reis + karamellisierte Zwiebeln)", source:"Yotam Ottolenghi – Jerusalem", technique:"Multi-Textur: Linsen 40 Min., Zwiebeln separat", check:"Zwiebeln dunkel karamellisiert, Linsen nicht matschig?", ownBook:false },
  { w:74, phase:2, theme:"Nahöstlich III: Hummus", dish:"Hummus (von Grund auf, Kichererbsen kochen)", source:"Ottolenghi – Jerusalem", technique:"Kichererbsen weichkochen, Tahini, Eiswasser", check:"Cremig-glatt, keine Stückchen?", ownBook:false },
  { w:75, phase:2, theme:"Nahöstlich IV: Cauliflower Steak", dish:"Blumenkohl-Steak mit Granatapfel", source:"Ottolenghi – Plenty / Jerusalem", technique:"Ganzes Gemüse behandeln, Rösten, Drizzle-Technik", check:"Blumenkohl durch, Oberfläche karamellisiert?", ownBook:false },
  pw(76,2,"Italienisch: Gnocchi di patate"), pw(77,2,"Japanisch: Soba-Nudeln von Hand"), pw(78,2,"Chinesisch: Dan Dan Noodles"),
  pw(79,2,"Fermentation-Einführung: Sauerkraut"), pw(80,2,"Nahöstlich: Shakshuka & Fladenbrot"), pw(81,2,"Spanisch: Paella Valenciana"),
  pw(82,2,"Koreanisch: Tteokbokki & Reiskuchen"), pw(83,2,"Österreichisch: Apfelstrudel"), pw(84,2,"Deutsch: Spätzle & Maultaschen"),
  pw(85,2,"Mexikanisch: Tamales"), pw(86,2,"Japanisch: Okonomiyaki"), pw(87,2,"Italienisch: Saltimbocca alla romana"),
  pw(88,2,"Chinesisch: Hainanese Chicken Rice"), pw(89,2,"Nahöstlich: Falafel & Pita"), pw(90,2,"Französisch: Bouillabaisse"),
  pw(91,2,"Japanisch: Gyoza von Hand"), pw(92,2,"Spanisch: Gazpacho & Salmorejo"), pw(93,2,"Koreanisch: Bibimbap"),
  pw(94,2,"Mexikanisch: Pozole"), pw(95,2,"Österreichisch: Gulasch"), pw(96,2,"Italienisch: Tiramisu"),
  pw(97,2,"Deutsch: Schwarzwälder Kirschtorte"), pw(98,2,"Spanisch: Crema Catalana"), pw(99,2,"Chinesisch: Peking-Stil Meeresfrüchte"),
  pw(100,2,"Wiederholung: Schwächste Wochen der Phase"), pw(101,2,"Japanisch: Katsu Curry"), pw(102,2,"Nahöstlich: Mansaf"),
  pw(103,2,"Kaiseki-inspiriertes 5-Gänge-Weltküchen-Menü"), pw(104,2,"Phase-2-Abschluss & Reflexion"),

  // ════════════════════════════════════════════════════════════════════════
  // PHASE 3: FORTGESCHRITTENE TECHNIKEN (Wochen 105–156)
  // ════════════════════════════════════════════════════════════════════════

  { w:105, phase:3, theme:"Sous-Vide I: 72h Short Ribs", dish:"72h Short Ribs (57°C)", source:"Thomas Keller – Under Pressure", technique:"Vakuumieren, Temperaturkontrolle, Nachbehandlung", check:"Zart trotz niedriger Temperatur? Kruste nachher?", ownBook:true },
  { w:106, phase:3, theme:"Sous-Vide II: Lachs mi-cuit", dish:"Lachs mi-cuit (40°C)", source:"Thomas Keller – Under Pressure", technique:"Niedrigtemperatur, Textur glasig-seidig", check:"Lachs innen noch transluzent am Rand?", ownBook:true },
  { w:107, phase:3, theme:"Sous-Vide III: Das 64°C-Ei", dish:"64°C-Ei + Varianten (66°C, 75°C)", source:"ChefSteps / Dave Arnold", technique:"Temperatur = Textur, Ei als Experiment", check:"Eigelb cremig, Eiweiß gerade gesetzt?", ownBook:false },
  { w:108, phase:3, theme:"Fermentation I: Lacto-Fermentation", dish:"Lacto-fermentiertes Gemüse (pH-Kontrolle)", source:"René Redzepi – Noma Guide to Fermentation", technique:"Salz, pH 4.6, anaerobe Umgebung", check:"pH unter 4.6? Bläschen aktiv?", ownBook:false },
  { w:109, phase:3, theme:"Fermentation II: Obst-Fermentation", dish:"Fermentiertes Obst (Pflaumen, Beeren)", source:"Redzepi – Noma Guide", technique:"Heimwerd, Reifekontrolle, Zeitmanagement", check:"Säure ausbalanciert, nicht alkoholisch?", ownBook:false },
  { w:110, phase:3, theme:"Fermentation III: Koji-Kultur", dish:"Koji-Reis ansetzen (Aspergillus oryzae)", source:"Redzepi – Noma Guide / Sandor Katz", technique:"Koji-Anbau, Aminosäuren, enzymatischer Abbau", check:"Weißer Pilzflaum gleichmäßig nach 48h?", ownBook:false },
  { w:111, phase:3, theme:"Fermentation IV: Kombucha & SCOBY", dish:"Kombucha (Grundrezept + Zweitfermentation)", source:"Sandor Katz – Art of Fermentation", technique:"SCOBY-Pflege, Zweitfermentation, Geschmack steuern", check:"Karbonisierung vorhanden, nicht zu sauer?", ownBook:false },
  { w:112, phase:3, theme:"Fermentation V: Miso (Langzeitprojekt)", dish:"Miso ansetzen (6+ Monate)", source:"Redzepi – Noma Guide", technique:"Koji + Sojabohnen, Langzeitfermentation", check:"Miso gestartet, Oberfläche stabil?", ownBook:false },
  { w:113, phase:3, theme:"Molekular I: Mango-Ravioli (Sphärifikation)", dish:"Mango-Ravioli (Natriumalginat + Calciumchlorid)", source:"Ferran Adrià – A Day at elBulli", technique:"Sphärifikation: Dosierung, Timing, Spülen", check:"Membran hält, flüssiger Kern?", ownBook:false },
  { w:114, phase:3, theme:"Molekular II: Agar-Fluid-Gel", dish:"Rote-Bete-Fluid-Gel", source:"Heston Blumenthal – Fat Duck Cookbook", technique:"Agar setzen, dann mixen zu Fluid-Gel", check:"Gel fließt, aber hält Form auf dem Löffel?", ownBook:false },
  { w:115, phase:3, theme:"Molekular III: Espuma (ISI-Siphon)", dish:"Espuma (Schaum, verschiedene Basen)", source:"Ferran Adrià / Grant Achatz – Alinea", technique:"Sahnekapseln, Fettgehalt, Lecithin-Air", check:"Schaum hält 5+ Minuten auf dem Teller?", ownBook:false },
  { w:116, phase:3, theme:"Molekular IV: Passionsfrucht-Schaum + Schokolade", dish:"Passionsfrucht-Schaum mit Schokolade", source:"Grant Achatz – Alinea / ChefSteps", technique:"Lecithin-Air, Säure-Bitter-Balance", check:"Schaum hauchzart auf der Zunge?", ownBook:false },
  { w:117, phase:3, theme:"Molekular V: Vakuum-Kompression", dish:"Komprimierte Wassermelone (+ Feta, Oliven)", source:"Thomas Keller – Under Pressure", technique:"Vakuum drückt Flüssigkeit in Zellen, Textur-Transformation", check:"Wassermelone nicht mehr schwammig, dicht wie Thunfisch?", ownBook:true },
  { w:118, phase:3, theme:"ISI-Infusion (Rapid Infusion)", dish:"Aromatisierte Öle/Flüssigkeiten (60 Sek.)", source:"Dave Arnold – Liquid Intelligence", technique:"Siphon-Methode, Druckanwendung, Schnellextraktion", check:"Aroma intensiv wie nach Tagen Ziehzeit?", ownBook:false },
  { w:119, phase:3, theme:"Hydrokolloid-Techniken: Gellan, Xanthan", dish:"Rote-Bete-Mosaik (versch. Gele)", source:"Modernist Cooking + Heston Blumenthal", technique:"Agar (fest), Gellan (low-acyl = elastisch), Fluid-Gel", check:"Unterschied zwischen Gelen erklären und demonstrieren?", ownBook:false },
  { w:120, phase:3, theme:"Sauce vierge & Roh-Küche", dish:"Sauce vierge (Tomatenwürfel, Olivenöl, Basilikum)", source:"Alain Ducasse", technique:"Rohes in der Fine-Dining-Tradition, Temperaturkontrolle", check:"Sauce frisch, Komponenten intakt trotz 60°C?", ownBook:false },
  pw(121,3,"Räuchern I: Kaltgeräucherter Lachs-Gravlax"), pw(122,3,"Räuchern II: Bresaola (luftgetrocknetes Rind)"),
  pw(123,3,"Croissants (27 Schichten, Laminage)"), pw(124,3,"Kouign-amann"), pw(125,3,"Entremets (Spiegel-Glasur-Torte)"),
  pw(126,3,"Praliné & Schokoladenarbeit"), pw(127,3,"Karamell-Techniken (106°C–170°C)"), pw(128,3,"Zucker ziehen: Isomalt, Engelshaar"),
  pw(129,3,"Tarte Tatin & Dehydrierung"), pw(130,3,"Umami-Pulver (Pilz-Dehydrierung)"), pw(131,3,"Emulsions-Meisterschaft (Beurre-Blend)"),
  pw(132,3,"Jakobsmuscheln & Beurre noisette"), pw(133,3,"Fisch: Champagner-Sauce, Haute Cuisine"), pw(134,3,"Makrele flammen (Blowtorch)"),
  pw(135,3,"Foie-gras-Terrine (en croûte)"), pw(136,3,"Filetsteak: Reverse Sear + Rotweinjus"), pw(137,3,"Terrine II: Vegetarische Variante"),
  pw(138,3,"Anrichten I: Punkte, Linien, Squeeze-Bottles"), pw(139,3,"Anrichten II: Mono-Produkt-Teller"), pw(140,3,"Anrichten III: Mille-feuille von Wurzelgemüse"),
  pw(141,3,"Dashi-Perfektion & Wagyu"), pw(142,3,"Umami-Synergie (Glutamat + Inosinat)"), pw(143,3,"Eigelb-Raviolo & Texturen"),
  pw(144,3,"Bottura: 5 Texturen in einem Gericht"), pw(145,3,"Schweinekruste & Knuspern"), pw(146,3,"Lavendel & Multi-Sensorik"),
  pw(147,3,"Degustationsmenü I: 5-Gänge"), pw(148,3,"Degustationsmenü II: Amuse + Crudo"), pw(149,3,"Koji-Glasur & Koji-Butter"),
  pw(150,3,"Food-Fotografie: Hero Dish"), pw(151,3,"Wiederholung: Schwächste Techniken"), pw(152,3,"Molekular-Wiederholung"),
  pw(153,3,"Fermentations-Check (Miso, Kombucha, Kimchi)"), pw(154,3,"Phase-3-Prüfung: Komplettes Degustationsmenü"),
  pw(155,3,"Reflexion & Feedback"), pw(156,3,"Phase-3-Abschluss"),

  // ════════════════════════════════════════════════════════════════════════
  // PHASE 4: MEISTERSCHAFT (Wochen 157–208)
  // ════════════════════════════════════════════════════════════════════════

  pw(157,4,"Wiederholung: Gougères + Crème fraîche + Kaviar"), pw(158,4,"Consommé perfektionieren"),
  pw(159,4,"Saisonales Menü: Frühling (Erbsen, Spargel, Morcheln)"), pw(160,4,"Saisonales Menü: Sommer (Tomate, Burrata, Basilikum)"),
  pw(161,4,"Saisonales Menü: Herbst (Kürbis, Wild, Brombeeren)"), pw(162,4,"Saisonales Menü: Winter (Kartoffel, Trüffel, Maronen)"),
  pw(163,4,"Tee-Zeremonie I: Japanisch (Matcha, Sencha, Gyokuro)"), pw(164,4,"Tee-Zeremonie II: Chinesisch (Gongfu, Pu-erh, Oolong)"),
  pw(165,4,"Tee & Food Pairing"), pw(166,4,"Dim-Sum-Auswahl (Jasmin-Tee-Stil)"),
  pw(167,4,"Kombucha-Programm: Trinkessig & Shrubs"), pw(168,4,"Alkoholfreie Getränke: Cocktail-Logik ohne Alkohol"),
  pw(169,4,"Alkoholfreie Getränke II: Kaffee & Kakao-Soda"), pw(170,4,"Enzym-Sirup & Tonic"), pw(171,4,"Yuzu-Ingwer-Erfrischung"),
  pw(172,4,"Risotto-Meisterschaft"), pw(173,4,"Steak neu definieren: Jenseits von Medium"), pw(174,4,"Sashimi: Rohfisch-Perfektion"),
  pw(175,4,"Miso-Aubergine & Soba"), pw(176,4,"Dekonstruktion: Tafelspitz neu gedacht"), pw(177,4,"Kaiserschmarrn-Zweitversion"),
  pw(178,4,"Petits fours (Financier, Pâte de fruit)"), pw(179,4,"Parfait & Tuile"), pw(180,4,"Sauerteig-Starter (Robertson-Methode)"),
  pw(181,4,"Sauerteig-Brot perfektionieren"), pw(182,4,"Zusammengesetztes Menü: Jus, Fonds, Reduktionen"),
  pw(183,4,"Signatur-Gericht entwickeln I"), pw(184,4,"Signatur-Gericht entwickeln II"), pw(185,4,"Signatur-Gericht entwickeln III (mit Twist)"),
  pw(186,4,"Dein Charakter als Koch definieren"), pw(187,4,"Speed & Systeme: Mise en place"), pw(188,4,"Küchenorganisation: Gordon Ramsay-Niveau"),
  pw(189,4,"Qualitätskontrolle & Timing"), pw(190,4,"Teamwork-Simulation: Caesar Salad unter Zeitdruck"),
  pw(191,4,"Dramatisches Servieren: Tableside"), pw(192,4,"Degustationsmenü: 7-Gänge (kontrolliert)"),
  pw(193,4,"Food-Fotografie II: Styling & Hero Shot"), pw(194,4,"Reflexion: Was war am schwierigsten?"),
  pw(195,4,"Pop-up / Supper Club planen"), pw(196,4,"Pop-up: Menü finalisieren"), pw(197,4,"Pop-up: Einkauf & Vorbereitung"),
  pw(198,4,"Pop-up: Durchführung"), pw(199,4,"Wettbewerb oder Community-Event"), pw(200,4,"Feedback sammeln & einarbeiten"),
  pw(201,4,"Wiederholung: Deine 5 schwächsten Wochen"), pw(202,4,"Letzte Verfeinerung I"), pw(203,4,"Letzte Verfeinerung II"),
  pw(204,4,"Finale Prüfung: 7-Gänge-Degustationsmenü"), pw(205,4,"Portfolio zusammenstellen"),
  pw(206,4,"Abschluss: Du weißt, wohin es weitergeht"), pw(207,4,"Letzte Reflexion & Zukunftsplan"),
  pw(208,4,"GESCHAFFT – 208 Wochen vollendet"),
];
